"""Opportunity Radar core package."""

from .cli_app import RadarCliApp
from .config import (
    DieselDomainConfig,
    DieselDictionaries,
    DieselExclusions,
    KeywordSearchSettings,
    ReportSettings,
    load_community_catalog,
    load_config,
    load_diesel_domain_config,
    write_community_catalog,
)
from .collector import (
    CollectionFailure,
    CollectionResult,
    RoundTwoCollectionResult,
    OpenCliCollector,
    ThreadComment,
    ThreadDocument,
)
from .deepseek import (
    AnalysisField,
    DEFAULT_BASE_URL,
    FLASH_MODEL,
    PRO_MODEL,
    DeepSeekClient,
    DeepSeekError,
    EvidenceClaim,
    HttpResponse,
    PostAnalysis,
    TopicCandidate,
)
from .evidence import (
    EVIDENCE_ROLES,
    EvidenceGateResult,
    EvidenceQuality,
    GatedEvidence,
    apply_diesel_evidence_gate,
    classify_diesel_evidence,
)
from .models import (
    Community,
    CommunityCatalog,
    CollectionSettings,
    NormalizedPost,
    PostWindow,
    RadarConfig,
    RunManifest,
    ShortlistedPost,
    TopicRecord,
    WindowedPost,
)
from .normalization import normalize_and_deduplicate
from .keywords import KeywordCandidate, build_topic_keyword_library, discover_diesel_keywords, select_round_two_terms
from .library import load_project_library, update_project_library
from .scoring import score_shortlist
from .storage import (
    TopicRegistry, RunPaths, append_failure, create_run_paths, persist_thread,
    read_manifest, write_keyword_library, write_manifest, write_normalized_records,
)
from .windowing import window_posts
from .topics import (
    EXCEL_SHEET_NAMES,
    EvidenceBackedClaim,
    PostSignal,
    ProTopicProposal,
    TopicAggregationResult,
    TopicAggregator,
    TopicEvidence,
    TopicExportArtifacts,
    build_community_library,
    export_topic_analysis,
)
from .report import build_topic_map, render_html

__all__ = [
    "Community",
    "AnalysisField",
    "CollectionSettings",
    "CollectionFailure",
    "CollectionResult",
    "RoundTwoCollectionResult",
    "DEFAULT_BASE_URL",
    "DeepSeekClient",
    "DeepSeekError",
    "DieselDomainConfig",
    "DieselDictionaries",
    "DieselExclusions",
    "CommunityCatalog",
    "EvidenceClaim",
    "EvidenceGateResult",
    "EvidenceQuality",
    "EVIDENCE_ROLES",
    "GatedEvidence",
    "EvidenceBackedClaim",
    "EXCEL_SHEET_NAMES",
    "FLASH_MODEL",
    "HttpResponse",
    "NormalizedPost",
    "OpenCliCollector",
    "PostWindow",
    "PostAnalysis",
    "PostSignal",
    "PRO_MODEL",
    "KeywordSearchSettings",
    "KeywordCandidate",
    "load_project_library",
    "update_project_library",
    "build_topic_keyword_library",
    "ReportSettings",
    "ProTopicProposal",
    "RadarCliApp",
    "RadarConfig",
    "RunManifest",
    "RunPaths",
    "ShortlistedPost",
    "TopicRecord",
    "TopicCandidate",
    "TopicAggregationResult",
    "TopicAggregator",
    "TopicEvidence",
    "TopicExportArtifacts",
    "build_community_library",
    "TopicRegistry",
    "WindowedPost",
    "ThreadComment",
    "ThreadDocument",
    "create_run_paths",
    "append_failure",
    "persist_thread",
    "write_normalized_records",
    "write_keyword_library",
    "load_community_catalog",
    "load_config",
    "load_diesel_domain_config",
    "normalize_and_deduplicate",
    "discover_diesel_keywords",
    "select_round_two_terms",
    "read_manifest",
    "score_shortlist",
    "window_posts",
    "write_manifest",
    "write_community_catalog",
    "export_topic_analysis",
    "build_topic_map",
    "render_html",
    "apply_diesel_evidence_gate",
    "classify_diesel_evidence",
]
